"""Trading signal model."""

from datetime import datetime

from sqlalchemy import DECIMAL, ForeignKey, String, Text, TIMESTAMP, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Signal(Base):
    """A trading signal generated by a strategy."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    strategy_id: Mapped[int | None] = mapped_column(
        ForeignKey("strategies.id", ondelete="SET NULL")
    )
    ticker: Mapped[str | None] = mapped_column(String(20))
    signal_type: Mapped[str | None] = mapped_column(String(50))
    confidence: Mapped[float | None] = mapped_column(DECIMAL(3, 2))
    raw_data: Mapped[str | None] = mapped_column(Text)   # JSON
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, server_default=func.now(), nullable=False
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    strategy: Mapped["Strategy"] = relationship(  # noqa: F821
        back_populates="signals", foreign_keys=[strategy_id]
    )

    def __repr__(self) -> str:
        return (
            f"<Signal id={self.id} ticker={self.ticker!r} "
            f"type={self.signal_type!r} confidence={self.confidence}>"
        )
